
# Database Configuration
POSTGRES_USER=postgres
POSTGRES_PASSWORD=1234
POSTGRES_DB=postgres

POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432

# Redis Configuration
REDIS_PASSWORD=1234
REDIS_HOST=judge0-redis
REDIS_PORT=6379

# Security and Resource Limits
# CPU Time Limit in seconds (Default 2 seconds)
CPU_TIME_LIMIT=2

# Wall Time Limit in seconds (Default 5 seconds)
WALL_TIME_LIMIT=5

# Memory Limit in kilobytes (256 MB)
MEMORY_LIMIT=262144

# Max File Size in kilobytes (10 MB)
MAX_FILE_SIZE=10240

# Prevent fork bombs and resource abuse by limiting processes and open files
MAX_PROCESSES_AND_OR_THREADS=64
MAX_FILE_DESCRIPTORS=256

# Disable telemetry if needed
# TELEMETRY_ENABLE=false
